In [1]:
import numpy as np

1.Soru:
0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.

In [12]:
arr1=np.arange(30)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
arr1.reshape(15,2)


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

2.Soru:
60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

In [15]:
arr2=np.random.randint(0,100,60)
arr2

array([86, 57, 39, 36, 74, 33, 20, 31, 87, 89, 73, 48, 79, 36, 24, 16, 73,
       69,  4, 37, 69, 26, 77, 77,  2, 37, 92, 87, 76, 47, 80, 57, 40, 18,
       51, 17, 85, 54, 58, 27, 43, 96, 43, 72,  6, 51, 55, 75, 87, 38, 14,
       90, 53, 63, 78, 30, 85, 45, 26, 54])

In [18]:
arr2=arr2.reshape(3,5,-1)
arr2

array([[[86, 57, 39, 36],
        [74, 33, 20, 31],
        [87, 89, 73, 48],
        [79, 36, 24, 16],
        [73, 69,  4, 37]],

       [[69, 26, 77, 77],
        [ 2, 37, 92, 87],
        [76, 47, 80, 57],
        [40, 18, 51, 17],
        [85, 54, 58, 27]],

       [[43, 96, 43, 72],
        [ 6, 51, 55, 75],
        [87, 38, 14, 90],
        [53, 63, 78, 30],
        [85, 45, 26, 54]]])

In [19]:
arr2.shape

(3, 5, 4)

In [21]:
arr2.ndim

3

3.Soru:
20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

In [24]:
arr3=np.random.randint(0,100,size=(4,5))
arr3

array([[10, 20, 31, 24, 24],
       [57, 78, 25, 61, 60],
       [38, 31, 61, 89, 12],
       [ 1, 83, 25, 54, 57]])

In [25]:
arr=arr3.reshape(-1)
arr

array([10, 20, 31, 24, 24, 57, 78, 25, 61, 60, 38, 31, 61, 89, 12,  1, 83,
       25, 54, 57])

4.Soru:
İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.

In [34]:
arr4=np.random.randint(0,100,size=(3,3,3))
arr4

array([[[34, 94, 38],
        [96, 32, 20],
        [38, 78, 65]],

       [[68, 85, 39],
        [66, 40, 27],
        [ 5, 57, 74]],

       [[25, 79, 70],
        [ 1, 27,  5],
        [42, 21, 92]]])

In [35]:
for i in arr4:
  for j in i:
      for a in j:
        print(a)

34
94
38
96
32
20
38
78
65
68
85
39
66
40
27
5
57
74
25
79
70
1
27
5
42
21
92


In [36]:
for i in np.nditer(arr4):
  print(i)

34
94
38
96
32
20
38
78
65
68
85
39
66
40
27
5
57
74
25
79
70
1
27
5
42
21
92


5.Soru:
5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve

   1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.

In [44]:
arr5=np.arange(5,31,5)
arr6=np.arange(1,7)

In [45]:
arr5+arr6

array([ 6, 12, 18, 24, 30, 36])

In [46]:
arr5-arr6

array([ 4,  8, 12, 16, 20, 24])

In [47]:
arr5*arr6

array([  5,  20,  45,  80, 125, 180])

In [50]:
arr5/arr6

array([5., 5., 5., 5., 5., 5.])

6.Soru:
0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.

In [52]:
arr7=np.random.randint(0,100,10)
arr7

array([43, 69, 54, 61, 67, 31, 14, 28,  8,  5])

In [53]:
arr7.sum()

380

In [54]:
arr7.mean()

38.0

In [55]:
arr7.max()

69

In [56]:
arr7.var()

532.6

In [57]:
arr7.std()

23.078128173662613

7.Soru:
0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.

In [62]:
arr8=np.random.randint(0,20,10)
arr8

array([ 1,  5,  7,  8,  0,  0, 14,  8, 14,  4])

In [63]:
arr9=np.random.randint(500,531,10)
arr9

array([508, 520, 525, 527, 530, 518, 512, 508, 513, 525])

In [66]:
np.concatenate([arr8,arr9],axis=0)

array([  1,   5,   7,   8,   0,   0,  14,   8,  14,   4, 508, 520, 525,
       527, 530, 518, 512, 508, 513, 525])

8.Soru:
15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.

In [67]:
arr10=np.random.randint(15,51,20)
arr10

array([25, 36, 46, 23, 18, 42, 18, 26, 45, 38, 47, 23, 43, 17, 41, 33, 22,
       32, 39, 37])

In [68]:
arr11=np.random.randint(10,101,20)
arr11

array([ 85,  91,  88,  86,  63,  52,  98,  63,  61,  24, 100,  14,  68,
        91,  89,  99,  70,  37,  97,  31])

In [71]:
arr_total=np.concatenate([arr10,arr11],axis=0)
arr_total

array([ 25,  36,  46,  23,  18,  42,  18,  26,  45,  38,  47,  23,  43,
        17,  41,  33,  22,  32,  39,  37,  85,  91,  88,  86,  63,  52,
        98,  63,  61,  24, 100,  14,  68,  91,  89,  99,  70,  37,  97,
        31])

In [90]:
arr_total[25:51]=888
arr_total

array([ 25,  36,  46,  23,  18,  42,  18,  26,  45,  38,  47,  23,  43,
        17,  41,  33,  22,  32,  39,  37,  85,  91,  88,  86,  63, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888])

9.Soru:0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.


In [72]:
arr12=np.random.randint(0,40,size=(8,5))
arr12

array([[ 9, 37, 22,  8,  6],
       [34,  1, 14, 17,  8],
       [12,  4, 36, 15, 12],
       [27, 14,  2, 34, 29],
       [20,  8, 24, 28,  0],
       [25, 12,  5, 29, 38],
       [11, 36, 35, 35, 13],
       [25, 34,  1, 28, 36]])

In [73]:
arr13=np.random.randint(320,361,size=(8,5))
arr13

array([[326, 324, 320, 358, 353],
       [338, 357, 355, 338, 320],
       [342, 358, 360, 352, 324],
       [336, 355, 339, 347, 330],
       [340, 353, 338, 337, 345],
       [358, 354, 329, 337, 327],
       [338, 337, 338, 337, 329],
       [324, 342, 337, 326, 352]])

In [75]:
np.concatenate([arr12,arr13],axis=0)

array([[  9,  37,  22,   8,   6],
       [ 34,   1,  14,  17,   8],
       [ 12,   4,  36,  15,  12],
       [ 27,  14,   2,  34,  29],
       [ 20,   8,  24,  28,   0],
       [ 25,  12,   5,  29,  38],
       [ 11,  36,  35,  35,  13],
       [ 25,  34,   1,  28,  36],
       [326, 324, 320, 358, 353],
       [338, 357, 355, 338, 320],
       [342, 358, 360, 352, 324],
       [336, 355, 339, 347, 330],
       [340, 353, 338, 337, 345],
       [358, 354, 329, 337, 327],
       [338, 337, 338, 337, 329],
       [324, 342, 337, 326, 352]])

In [76]:
np.concatenate([arr12,arr13],axis=1)

array([[  9,  37,  22,   8,   6, 326, 324, 320, 358, 353],
       [ 34,   1,  14,  17,   8, 338, 357, 355, 338, 320],
       [ 12,   4,  36,  15,  12, 342, 358, 360, 352, 324],
       [ 27,  14,   2,  34,  29, 336, 355, 339, 347, 330],
       [ 20,   8,  24,  28,   0, 340, 353, 338, 337, 345],
       [ 25,  12,   5,  29,  38, 358, 354, 329, 337, 327],
       [ 11,  36,  35,  35,  13, 338, 337, 338, 337, 329],
       [ 25,  34,   1,  28,  36, 324, 342, 337, 326, 352]])

10.Soru:
9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.

In [84]:
arr=arr12.reshape(2,5,4)
arr


array([[[ 9, 37, 22,  8],
        [ 6, 34,  1, 14],
        [17,  8, 12,  4],
        [36, 15, 12, 27],
        [14,  2, 34, 29]],

       [[20,  8, 24, 28],
        [ 0, 25, 12,  5],
        [29, 38, 11, 36],
        [35, 35, 13, 25],
        [34,  1, 28, 36]]])

In [86]:
arr1=arr13.reshape(2,5,4)
arr1


array([[[326, 324, 320, 358],
        [353, 338, 357, 355],
        [338, 320, 342, 358],
        [360, 352, 324, 336],
        [355, 339, 347, 330]],

       [[340, 353, 338, 337],
        [345, 358, 354, 329],
        [337, 327, 338, 337],
        [338, 337, 329, 324],
        [342, 337, 326, 352]]])

In [82]:
np.concatenate([arr,arr1],axis=2)

array([[[  9,  37,  22,   8, 326, 324, 320, 358],
        [  6,  34,   1,  14, 353, 338, 357, 355],
        [ 17,   8,  12,   4, 338, 320, 342, 358],
        [ 36,  15,  12,  27, 360, 352, 324, 336],
        [ 14,   2,  34,  29, 355, 339, 347, 330]],

       [[ 20,   8,  24,  28, 340, 353, 338, 337],
        [  0,  25,  12,   5, 345, 358, 354, 329],
        [ 29,  38,  11,  36, 337, 327, 338, 337],
        [ 35,  35,  13,  25, 338, 337, 329, 324],
        [ 34,   1,  28,  36, 342, 337, 326, 352]]])

11.Soru:
[1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.

In [93]:
arr2=np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
np.where(arr2==5)

(array([ 5, 13]),)

12.Soru:
Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.

In [95]:
np.where(arr2%2==0)

(array([ 1,  3,  4,  6,  7,  9, 11]),)

13.Soru:
Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.

In [96]:
np.where(arr2>4)

(array([ 1,  2,  5,  9, 10, 11, 13]),)

14.Soru:
Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.


In [97]:
np.where(arr2%5==0)

(array([ 1,  2,  5, 13]),)

15.Soru:
85-100(100 dahil) arasından rastgele 1 tam sayı seçin

In [98]:
arr3=np.random.randint(85,101,1)
arr3

array([93])

16.Soru
İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.

In [103]:
arr16=np.random.randint(10,100,size=(3,3))
arr16

array([[83, 24, 68],
       [22, 71, 70],
       [88, 25, 67]])

17.Soru
35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.

In [109]:
arr17=np.random.randint(35,60,size=(2,3,4))
arr17

array([[[44, 50, 38, 45],
        [39, 59, 53, 40],
        [58, 38, 40, 56]],

       [[50, 55, 58, 49],
        [53, 36, 51, 47],
        [43, 38, 36, 58]]])

In [111]:
arr17[1,2,2]

36

18.soru:
Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.


In [114]:
arr18=np.array( [3, 8, 10, 53,3, 8, 10, 53,3, 8]).reshape(2,5)
arr18


array([[ 3,  8, 10, 53,  3],
       [ 8, 10, 53,  3,  8]])