In [2]:
import numpy as np

Mehmet Eraslan


In [29]:
#1.soru
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr.ndim

3

In [30]:
#2.soru
arr1=np.arange(34,113,6)
arr1

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

In [31]:
#3.soru
arr2=np.linspace(50,500,91,dtype=int)
arr2

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

In [32]:
#4.soru
arr3=np.logspace(2,5,8)
arr3

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

In [33]:
#5.soru
arr4=np.random.randint(0,9,(3,3))
arr4

array([[3, 7, 2],
       [0, 3, 6],
       [0, 7, 7]])

In [34]:
#6.soru
arr5=np.zeros((6,6),dtype=int)
arr5

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [35]:
#7.soru
arr6=np.ones((4,4),dtype=int)
arr6

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [36]:
#8.soru
arr7=np.eye(8,dtype="int")
arr7

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [39]:
#9.soru
arr8=np.eye(5,dtype="int")
arr8

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [47]:
arr8[0,0]=3
arr8[1,1]=3
arr8[2,2]=3
arr8[3,3]=3
arr8[4,4]=3
arr8

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

In [10]:
#10.soru
arr9=np.random.rand(6)
arr9


array([0.88476868, 0.78104336, 0.26034726, 0.66617862, 0.76252462,
       0.00274675])

In [12]:
#11.soru
arr10=np.random.randint(50,101,(5,2))
arr10
arr10.shape

(5, 2)

In [13]:
#12.soru
arr11=np.random.randint(100,1000,(2,5,5))
arr11

array([[[573, 988, 327, 643, 400],
        [426, 229, 810, 392, 824],
        [439, 178, 572, 159, 812],
        [863, 265, 831, 271, 826],
        [833, 187, 368, 325, 286]],

       [[729, 812, 520, 493, 635],
        [669, 615, 740, 751, 243],
        [966, 734, 371, 645, 696],
        [374, 694, 715, 371, 506],
        [196, 992, 639, 772, 266]]])

In [14]:
arr11.ndim

3

In [15]:
arr11.shape

(2, 5, 5)

In [17]:
#13.soru
arr12=np.random.randint(0,100,size=10)
arr12

array([ 7, 27, 96, 75, 39,  8, 75, 31, 29, 98])

In [18]:
arr12.max()

98

In [19]:
arr12.argmax()

9

In [22]:
arr12.min()

7

In [23]:
arr12.argmin()

0

In [24]:
#14.soru
arr13=np.random.randint(300,501,(2,5,5))
arr13

array([[[433, 446, 476, 405, 410],
        [462, 331, 455, 413, 486],
        [477, 312, 472, 489, 360],
        [370, 309, 338, 375, 428],
        [448, 421, 412, 442, 475]],

       [[393, 489, 300, 380, 429],
        [341, 482, 323, 416, 404],
        [419, 461, 439, 436, 473],
        [472, 456, 371, 448, 436],
        [473, 313, 500, 304, 428]]])

In [26]:
arr13[1,4,2]

500

In [28]:
arr13[1,4,3]

304